### ISSUE TITLE
Cannot install add-on

### ISSUE THREAD

**Issue by rntheandrian** [johnzero7/XNALaraMesh#100]
I am running Blender 2.74 and going to install XNALaraMesh 1.8.x. However, I am unable to install any version of the XNALaraMesh due to an error. I can't seem to find a precise solution for this problem so any help would be appreciated.

The following is the error in question:
`Traceback (most recent call last):`
``File "C:\Program Files\Blender Foundation\Blender\2.74\scripts\modules\addons\addons_utils.py", line 306, in enable mod = __import__(module_name)``
``File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.74\scripts\addons\XNALaraMesh\__init__.py", line 57, in <module> from XNALaraMesh import xps_tools``
`ImportError: cannot import name 'xps_tools'`

**Comment by Czarinadimaranan** [comment]
same

**Comment by LucasAlfare** [comment]
This addddon probably works only with Blender 2.7x versions.

**Comment by Yuraass** [comment]
Did you solve the problem?
