### ISSUE TITLE
errors appear when I open a mesh file

### ISSUE THREAD

**Issue by Quriosity0** [johnzero7/XNALaraMesh#113]
Python: Traceback (most recent call last):
  File "C:\Users\TheNightHairen\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XNALaraMesh\xps_tools.py", line 164, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TheNightHairen\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 78, in getInputFilename
    status = xpsImport()
             ^^^^^^^^^^^
  File "C:\Users\TheNightHairen\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 159, in xpsImport
    meshes_obs = importMeshesList(armature_ob)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TheNightHairen\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 477, in importMeshesList
    importedMeshes = [importMesh(armature_ob, meshInfo)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TheNightHairen\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 477, in <listcomp>
    importedMeshes = [importMesh(armature_ob, meshInfo)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TheNightHairen\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 614, in importMesh
    material_creator.makeMaterial(xpsSettings, rootDir, mesh_da, meshInfo, flags)
  File "C:\Users\TheNightHairen\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XNALaraMesh\material_creator.py", line 164, in makeMaterial
    makeNodesMaterial(xpsSettings, materialData, rootDir, mesh_da, meshInfo, flags)
  File "C:\Users\TheNightHairen\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XNALaraMesh\material_creator.py", line 192, in makeNodesMaterial
    node_tree.links.new(xpsShadeNode.outputs['Shader'], ouputNode.inputs['Surface'])
                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Shader" not found'

**Comment by jaythefrog71** [comment]
i have the same issue
