### ISSUE TITLE
Error on Import (Blender 2.79 Daily Builds Oct 2017)

### ISSUE THREAD

**Issue by Gnates** [johnzero7/XNALaraMesh#14]
I don't know if the Blender developers unintentionally broke something or if they made some new adjustments that require addon developers to update their code.

**Working: Blender 2.79 Official Release**
**Broken: Blender 2.79 Buildbot (Hash: 83ce028 Date: 2017-10-06 16:06)**
**XPS_Tools v1.7.3**

Error when attempting to import an XPS model:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\xps_tools.py", line 141, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 172, in getInputFilename
    status = xpsImport()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\timing.py", line 12, in wrap
    ret = f(*args)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 275, in xpsImport
    meshes_obs = importMeshesList(armature_ob)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 628, in importMeshesList
    for meshInfo in newMeshes]
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 628, in <listcomp>
    for meshInfo in newMeshes]
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 760, in importMesh
    makeUvs(mesh_da, origFaces, uvLayers, vertColors)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 558, in makeUvs
    mesh_da.vertex_colors[0].data[loopdId].color = vertColors[faceVert]
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 4 items, not 3

location: <unknown location>:-1

**Comment by johnzero7** [comment]
Looks like the vertex color has been changed from a 3 component vector to a 4 components one. Maybe they are finally adding alpha to the vertex color.
I am updating the addon so it doesn't fail either if they add the alpha component or not.
