### ISSUE TITLE
[Blender 2.8 Beta - Addon v1.9.0] AttributeError: 'Context' object has no attribute 'user_preferences'

### ISSUE THREAD

**Issue by Irastris** [johnzero7/XNALaraMesh#34]
Attempting to use this addon in the latest build of Blender v2.8 results in the following error:

```
------------------------------------------------------------
---------------EXECUTING XPS PYTHON IMPORTER----------------
------------------------------------------------------------
Importing file:  [REDACTED]
File: [REDACTED]
Reading Header
Header Found
Reading Bones
Read 347 Bones
Reading Meshes
Read 39 Meshes
Importing Armature 347 bones

---*** Importing Mesh 24_base1_0.6_1_1 ***---
UV Layer Count: 1
Texture Count: 4
Created Mesh: 24_base1_0.6_1_1
New Mesh = 24_base1_0.6_1_1
Traceback (most recent call last):
  File "[REDACTED]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\xps_tools.py", line 144, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "[REDACTED]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 85, in getInputFilename
    status = xpsImport()
  File "[REDACTED]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 150, in xpsImport
    meshes_obs = importMeshesList(armature_ob)
  File "[REDACTED]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 466, in importMeshesList
    for meshInfo in newMeshes]
  File "[REDACTED]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 466, in <listcomp>
    for meshInfo in newMeshes]
  File "[REDACTED]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 611, in importMesh
    makeBoneGroups(armature_ob, mesh_ob)
  File "[REDACTED]\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 743, in makeBoneGroups
    current_theme = C.user_preferences.themes.items()[0][0]
AttributeError: 'Context' object has no attribute 'user_preferences'
```

As can be inferred by the log, a single mesh imports before the addon aborts due to being unable to read some user preferences. I checked and found that for reasons unknown to me, the user preferences panel is indeed failing.

![UP Panel Error](https://i.imgur.com/oHpUZBE.png "UP Panel Error")

Any suggestions? This error occurs with the master as well, not only v1.9.0.

**Comment by johnzero7** [comment]
The Blender 2.80 Beta devs are STILL introducing changes to the API. I can't keep up with nightly build changes, specially in these days. If you find and older version of blender 2.80 that works don't let it go :P

**Comment by Irastris** [comment]
Alright, thanks. In that case I'll just get the stable v2.79b for these purposes.
