### ISSUE TITLE
Error while enabling addon [Blender 2.79.7, addon 1.8.5]

### ISSUE THREAD

**Issue by Marcelievsky** [johnzero7/XNALaraMesh#46]
Hi!
I'm receiving the following error after I installed the addon:

addon_utils.disable: XNALaraMesh not disabled
Modules Installed (XNALaraMesh) from 'C:\\Users\\marce\\Downloads\\XNALaraMesh.1.8.5.zip' into 'C:\\Users\\marce\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files (x86)\blender-2.79.0-git.2adf4b401ed2-windows64\2.79\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\marce\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\__init__.py", line 54, in <module>
    __import__(name=__name__, fromlist=_modules)
  File "C:\Users\marce\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\XNALaraMesh\import_obj.py", line 44, in <module>
    from progress_report import ProgressReport, ProgressReportSubstep
ModuleNotFoundError: No module named 'progress_report'

This happens to 1.8.4 to 1.8.7

Any help is appreciated!

Thanks

**Comment by Gnates** [comment]
Does renaming the zip file from **XNALaraMesh1.8.7.zip** to **XNALaraMesh1-8-7.zip** allow you to install from zip successfully?

**Comment by johnzero7** [comment]
The problem were changes in the API made in stable version of 2.79
The addon is now compatible with Release and Stable versions of 2.79
