### ISSUE TITLE
i cant import files, in blender 2.8

### ISSUE THREAD

**Issue by Myoko** [johnzero7/XNALaraMesh#47]
hi, guys

i cant enable XPSTools v1.9.1 in blender 2.8 beta i got Keyerror

**Comment by ldo** [comment]
As a general rule, I would recommend you please do not post pictures of text error messages. Copy and paste the text itself.

I’m sure I speak for the maintainer of this repo, and for all other repo maintainers.

**Comment by Myoko** [comment]
blender-2.80-de9d846353bd

: bpy.context.space_data.recent_folders_active = 4
: bpy.context.space_data.recent_folders_active = 0
: bpy.context.space_data.recent_folders_active = 1
Error: Traceback (most recent call last):
  File "C:\Users\kkkik\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\xps_tools.py", line 138, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\kkkik\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 85, in getInputFilename
    status = xpsImport()
  File "C:\Users\kkkik\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 156, in xpsImport
    armature_ob = createArmature(xpsSettings.autoIk)
  File "C:\Users\kkkik\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 328, in createArmature
    armature_ob.data.use_auto_ik = autoIk
AttributeError: 'Armature' object has no attribute 'use_auto_ik'

location: <unknown location>:-1

: bpy.context.area.ui_type = 'TEXT_EDITOR'
Error: Traceback (most recent call last):
  File "C:\Users\kkkik\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\xps_tools.py", line 138, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\kkkik\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 85, in getInputFilename
    status = xpsImport()
  File "C:\Users\kkkik\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 156, in xpsImport
    armature_ob = createArmature(xpsSettings.autoIk)
  File "C:\Users\kkkik\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 328, in createArmature
    armature_ob.data.use_auto_ik = autoIk
AttributeError: 'Armature' object has no attribute 'use_auto_ik'

location: <unknown location>:-1

**Comment by RenderAdept** [comment]
Weird. According the 2.8 "Armature" doc, "use_auto_ik" is an attribute.
https://docs.blender.org/api/blender2.8/bpy.types.Armature.html

**Comment by CastelHQ** [comment]
`Traceback (most recent call last):
  File "C:\Users\Castel\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\xps_tools.py", line 138, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\Castel\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 85, in getInputFilename
    status = xpsImport()
  File "C:\Users\Castel\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 156, in xpsImport
    armature_ob = createArmature(xpsSettings.autoIk)
  File "C:\Users\Castel\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 328, in createArmature
    armature_ob.data.use_auto_ik = autoIk
AttributeError: 'Armature' object has no attribute 'use_auto_ik'

location: <unknown location>:-1

`

**Comment by CastelHQ** [comment]
Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\xps_tools.py", line 138, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 85, in getInputFilename
    status = xpsImport()
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 156, in xpsImport
    armature_ob = createArmature(xpsSettings.autoIk)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 328, in createArmature
    armature_ob.data.use_auto_ik = autoIk
AttributeError: 'Armature' object has no attribute 'use_auto_ik'

location: <unknown location>:-1

**Comment by CastelHQ** [comment]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\xps_tools.py", line 138, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 85, in getInputFilename
    status = xpsImport()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 156, in xpsImport
    armature_ob = createArmature(xpsSettings.autoIk)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 328, in createArmature
    armature_ob.data.use_auto_ik = autoIk
AttributeError: 'Armature' object has no attribute 'use_auto_ik'

location: <unknown location>:-1

**Comment by drewc5131** [comment]
> 
> 
> Weird. According the 2.8 "Armature" doc, "use_auto_ik" is an attribute.
> https://docs.blender.org/api/blender2.8/bpy.types.Armature.html

As of now it is no longer there

**Comment by johnzero7** [comment]
> > Weird. According the 2.8 "Armature" doc, "use_auto_ik" is an attribute.
> > https://docs.blender.org/api/blender2.8/bpy.types.Armature.html
> 
> As of now it is no longer there

Fixed. The use_auto_ik attribute has been moved to:
https://docs.blender.org/api/blender2.8/bpy.types.Pose.html
