### ISSUE TITLE
Error when trying to import .mesh or .xps in Blender 2.8

### ISSUE THREAD

**Issue by frankmodels89** [johnzero7/XNALaraMesh#48]
Hey guys,

I'm just trying to import some .mesh files with the plugin on 2.8, but nothing works. Using latest version (I think) of XNALaraMesh.

Here's the error log: (I've expunged my name, obviously) 

"Importing file:  C:\Users\Name\Downloads\FrankModels\generic_item.mesh
rootDir: C:\Users\Name\Downloads\FrankModels
File: C:\Users\Name\Downloads\FrankModels\generic_item.mesh
Reading Header
Header Found
Reading Bones
Read 109 Bones
Reading Meshes
Read 6 Meshes
Importing Armature 109 bones
Traceback (most recent call last):
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\xps_tools.py", line 138, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 85, in getInputFilename
    status = xpsImport()
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 156, in xpsImport
    armature_ob = createArmature(xpsSettings.autoIk)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh-master\import_xnalara_model.py", line 328, in createArmature
    armature_ob.data.use_auto_ik = autoIk
AttributeError: 'Armature' object has no attribute 'use_auto_ik'

location: <unknown location>:-1"

Is this something a new XNALara patch will fix, or am I screwed? Is there any solution at all? Help much appreciated. Thanks guys.

**Comment by frankmodels89** [comment]
Update: Used 1.8.7 in Blender 2.79 and the problem was resolved. I don't like 2.79's interface, but it's a sacrifice I'll have to make, I suppose. Hopefully, this will be patched for 2.8 someday.

**Comment by johnzero7** [comment]
Released v1.9.2 for Blender 2.80 fixing this change in the API.

According to Blender devs, API and interface should be frozen now. 
https://code.blender.org/2019/05/user-interface-and-api-freeze/
