### ISSUE TITLE
Problem on Blender 2.81

### ISSUE THREAD

**Issue by Danilopereira82** [johnzero7/XNALaraMesh#55]
Traceback (most recent call last):
  File "/home/danilop/.programas/blender-2.81-87c017985719-linux-glibc217-x86_64/2.81/scripts/addons/XNALaraMesh/xps_tools.py", line 164, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "/home/danilop/.programas/blender-2.81-87c017985719-linux-glibc217-x86_64/2.81/scripts/addons/XNALaraMesh/import_xnalara_model.py", line 78, in getInputFilename
    status = xpsImport()
  File "/home/danilop/.programas/blender-2.81-87c017985719-linux-glibc217-x86_64/2.81/scripts/addons/XNALaraMesh/import_xnalara_model.py", line 156, in xpsImport
    meshes_obs = importMeshesList(armature_ob)
  File "/home/danilop/.programas/blender-2.81-87c017985719-linux-glibc217-x86_64/2.81/scripts/addons/XNALaraMesh/import_xnalara_model.py", line 475, in importMeshesList
    for meshInfo in newMeshes]
  File "/home/danilop/.programas/blender-2.81-87c017985719-linux-glibc217-x86_64/2.81/scripts/addons/XNALaraMesh/import_xnalara_model.py", line 475, in <listcomp>
    for meshInfo in newMeshes]
  File "/home/danilop/.programas/blender-2.81-87c017985719-linux-glibc217-x86_64/2.81/scripts/addons/XNALaraMesh/import_xnalara_model.py", line 612, in importMesh
    material_creator.makeMaterial(xpsSettings, rootDir, mesh_da, meshInfo, flags)
  File "/home/danilop/.programas/blender-2.81-87c017985719-linux-glibc217-x86_64/2.81/scripts/addons/XNALaraMesh/material_creator.py", line 170, in makeMaterial
    makeNodesMaterial(xpsSettings, materialData, rootDir, mesh_da, meshInfo, flags)
  File "/home/danilop/.programas/blender-2.81-87c017985719-linux-glibc217-x86_64/2.81/scripts/addons/XNALaraMesh/material_creator.py", line 338, in makeNodesMaterial
    mappingCoordNode.scale = (texRepeater, texRepeater, texRepeater)
AttributeError: 'ShaderNodeMapping' object has no attribute 'scale'

location: <unknown location>:-1

**Comment by johnzero7** [comment]
Blender 2.81 is still Alpha and making constant changes.
I will wait for at least the RC before any attempt to use the addon.
