### ISSUE TITLE
Cant Enable Addon

### ISSUE THREAD

**Issue by Bisiak** [johnzero7/XNALaraMesh#60]
I am unable to enable addon (after adding) in recently downloaded blender 2.8 can someone help?

Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\blender-2.80.0-git.41cba97-windows64\2.80\scripts\modules\addon_utils.py", line 338, in enable
    mod = __import__(module_name)
  File "C:\Users\Bisiak\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\__init__.py", line 54, in <module>
    __import__(name=__name__, fromlist=_modules)
  File "C:\Users\Bisiak\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\XNALaraMesh\xps_tools.py", line 12, in <module>
    from bpy_extras.io_utils import (
ImportError: cannot import name 'orientation_helper'

**Comment by johnzero7** [comment]
Tested in released 2.80 and 2.81 and works fine.
The hash is from an old pre-realaese of 2.80.
Try updating blender.
