### ISSUE TITLE
No such file or directory (both 2.79b & 2.82a &2.8.0)

### ISSUE THREAD

**Issue by VinciShark** [johnzero7/XNALaraMesh#66]
```
Traceback (most recent call last):
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\XNALaraMesh\xps_tools.py", line 164, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 78, in getInputFilename
    status = xpsImport()
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 159, in xpsImport
    meshes_obs = importMeshesList(armature_ob)
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 478, in importMeshesList
    for meshInfo in newMeshes]
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 478, in <listcomp>
    for meshInfo in newMeshes]
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 614, in importMesh
    material_creator.makeMaterial(xpsSettings, rootDir, mesh_da, meshInfo, flags)
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\XNALaraMesh\material_creator.py", line 164, in makeMaterial
    makeNodesMaterial(xpsSettings, materialData, rootDir, mesh_da, meshInfo, flags)
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\XNALaraMesh\material_creator.py", line 216, in makeNodesMaterial
    imageNode.image = loadImage(imageFilepath)
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\XNALaraMesh\material_creator.py", line 135, in loadImage
    image = bpy.data.images.load(filepath=textureFilepath, check_existing=True)
RuntimeError: Error: Cannot read 'E:\Sekiro\parts\wp_a_0300-partsbnd-dcx\parts\Weapon\WP_A_0300\': No such file or directory


location: <unknown location>:-1


```

I tried both both 2.79b & 2.82a & 2.8.0, and different directory to store .ascii file

[I upload original .ascii & .flver file here](https://drive.google.com/drive/folders/1xhOGDYMAfLnKx7CWVW5qJ0R0y6UvhxsG?usp=sharing)

object should be:
![object should be](https://user-images.githubusercontent.com/9538504/78194017-8acc5580-74ae-11ea-9076-69c8ae5667be.png)

import to blender:
![import to blender](https://user-images.githubusercontent.com/9538504/78194021-8d2eaf80-74ae-11ea-9611-43d8c37d8673.png)

Really want to figure out why, thanks you.

**Comment by VinciShark** [comment]
@johnzero7

**Comment by VinciShark** [comment]
#67

**Comment by johnzero7** [comment]
Thanks for reporting the issue so clearly
It is fixed in master
