### ISSUE TITLE
KeyError: xps_panels when trying to install addon on blender 2.83.3

### ISSUE THREAD

**Issue by RadioactiveBananaZ** [johnzero7/XNALaraMesh#73]
Here's the full code
--------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\XNALaraMesh\__init__.py", line 57, in <module>
    _modules_loaded = [_namespace[name] for name in _modules]
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\XNALaraMesh\__init__.py", line 57, in <listcomp>
    _modules_loaded = [_namespace[name] for name in _modules]
KeyError: 'xps_panels'

**Comment by Vanedyn** [comment]
1st delethe the XNALaraMesh Folder from:
C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\
I fixed it by installing the addon in the appdata folder. 
C:\Users\ YOURUSERNAME \AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons
Pasthe here the XNALaraMesh Folder!.
If you do Win+R, write `appdata` and press Enter, it will lead you directly to the Roaming folder.
