### ISSUE TITLE
Import Problem .mesh Blender 2.8.3

### ISSUE THREAD

**Issue by DaemosOriginal** [johnzero7/XNALaraMesh#90]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\bin_ops.py", line 87, in readString
    string = decodeBytes(byteString)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\bin_ops.py", line 107, in decodeBytes
    return bytes.decode(xps_const.ENCODING_READ)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\encodings\utf_8_sig.py", line 23, in decode
    (output, consumed) = codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 4: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\xps_tools.py", line 164, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 78, in getInputFilename
    status = xpsImport()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 140, in xpsImport
    xpsData = loadXpsFile(xpsSettings.filename)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 104, in loadXpsFile
    xpsData = read_bin_xps.readXpsModel(filename)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\read_bin_xps.py", line 375, in readXpsModel
    bones = readBones(ioStream, xpsHeader)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\read_bin_xps.py", line 271, in readBones
    boneName = readFilesString(file)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\read_bin_xps.py", line 83, in readFilesString
    string = bin_ops.readString(file, length)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\bin_ops.py", line 95, in readString
    string = decodeBytes(byteString)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\XNALaraMesh\bin_ops.py", line 107, in decodeBytes
    return bytes.decode(xps_const.ENCODING_READ)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\encodings\utf_8_sig.py", line 23, in decode
    (output, consumed) = codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 4: invalid continuation byte

location: <unknown location>:-1

**Comment by InfGame** [comment]
I am getting the same error trying to import a .mesh file in blender 
3.2.2

**Comment by ldo** [comment]
Probably means what it says.
